name: IR via npm install

on:
  workflow_dispatch:
  
permissions:
  checks: write
  contents: write
  packages: read

jobs:
  python-application-build:
    runs-on: ubuntu-latest
    name: Run build
    steps:
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          api_url: "https://app.stage.invisirisk.com"
          app_token: ${{secrets.IR_API_KEY_STAGE_SH_SS}}
          
      - uses: actions/checkout@v4
      
      - name: Configure GitHub CLI and Git with PAT
        run: |
          echo "=== Configuring GitHub CLI with PAT ==="
          echo "$PAT" | gh auth login --with-token
          
          echo ""
          echo "=== Verifying GitHub CLI authentication ==="
          gh auth status
          
          echo ""
          echo "=== Getting authenticated user info ==="
          gh api user --jq '.login + " (" + .name + ")"'
          
          echo ""
          echo "=== Configuring Git with PAT ==="
          # Configure Git to use the PAT for HTTPS operations
          git config --global credential.helper store
          echo "https://x-access-token:${PAT}@github.com" > ~/.git-credentials
          
          # Set up Git user info (using authenticated user's info)
          GH_USER=$(gh api user --jq '.login')
          GH_EMAIL=$(gh api user --jq '.email // (.login + "@users.noreply.github.com")')
          git config --global user.name "$GH_USER"
          git config --global user.email "$GH_EMAIL"
          
          echo ""
          echo "=== Verifying Git configuration ==="
          echo "Git user.name: $(git config --global user.name)"
          echo "Git user.email: $(git config --global user.email)"
          
          echo ""
          echo "=== Testing Git authentication with remote ==="
          # Test authentication by checking remote access
          git ls-remote --heads origin > /dev/null 2>&1
          if [ $? -eq 0 ]; then
            echo "✓ Git authentication successful - can access remote repository"
          else
            echo "⚠ Git authentication may have issues accessing remote"
          fi
          
          echo ""
          echo "=== GitHub CLI and Git are now configured with PAT ==="

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@latest
        with:
          cleanup: "true"
