name: Install nx@21.7.0 (local tarball)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@v4

      - name: Authenticate GH CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Verify login
        run: gh auth status

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # or whichever Node.js version you need

      - name: Install nx@21.7.0 from local file
        run: npm install ./nx-21.7.0.tgz
